# site settings
title: LouisChenAstro
subtitle: Personal Blog
email: cchen_louis@stu.pku.edu.cn
description: I am currently a third-year Ph.D student at the Kavli Institute of Astronomy and Astrophysics (KIAA) in Beijing. Here is a link to my ADS page if you want to quickly know me as a researcher.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://louischen-ustc.github.io/"# the base hostname & protocol for your site
author: Louis Chen
street_address: No.5, Yiheyuan Road, Haidian District, Beijing, P.R. China
city: Beijing
state: 
zip_code: 100871
country: P.R. China
phone: +86 13501398392

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/andrewbanchich
  GitLab:
  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram:
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  Twitter: https://twitter.com/andrewbanchich
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
